apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.3.100:6443
    token: w24ybw.6qz7jzxhzmn9v5w5
    unsafeSkipCAVerification: true
  tlsBootstrapToken: w24ybw.6qz7jzxhzmn9v5w5