version: '3'
services:
  mongo:
    image: mongo:4.2.3
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hcq@
    ports:
      - '27017:27017'
    volumes:
      - '/docker/mongodb_dir/data/db:/data/db'
    restart: always

  mysql:
    image: mysql:8.0.18
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - '/docker/mysql_dir/var/lib/mysql:/var/lib/mysql'
      - '/docker/mysql_dir/etc/mysql/conf.d:/etc/mysql/conf.d'
      - '/docker/mysql_dir/var/log:/var/log'
    environment:
      MYSQL_ROOT_PASSWORD: 'hcq@'
    restart: always

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins_master
    user: root
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - '/docker/jenkins_dir/var/jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always

  ubuntu:
    image: ubuntu:22.04
    #    build: ./add_jenkins_node/
    container_name: jenkins_service_1
    network_mode: 'host'
    volumes:
      - '/docker/ubuntu_dir/tmp:/tmp'
      - './add_jenkins_node.sh:/add_jenkins_node.sh' #进入容器执行该脚本
    command: /bin/bash
    tty: true
    restart: always

  gerrit:
    image: gerritcodereview/gerrit
    container_name: gerrit
    ports:
      - "29418:29418"
      - "8089:8080"
    depends_on:
      - ldap
    volumes:
      - /docker/gerrit_dir/var/gerrit/etc:/var/gerrit/etc
      - /docker/gerrit_dir/var/gerrit/git:/var/gerrit/git
      - /docker/gerrit_dir/var/gerrit/db:/var/gerrit/db
      - /docker/gerrit_dir/var/gerrit/index:/var/gerrit/index
      - /docker/gerrit_dir/var/gerrit/cache:/var/gerrit/cache
    environment:
      - CANONICAL_WEB_URL=http://116.63.170.231:8089
    # command: init
    restart: always

  ldap:
    image: osixia/openldap
    container_name: openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ADMIN_PASSWORD=hcq@
    volumes:
      - /docker/gerrit_dir/var/gerrit/ldap/var:/var/lib/ldap
      - /docker/gerrit_dir/var/gerrit/ldap/etc:/etc/ldap/slapd.d
    restart: always

  ldap-admin:
    image: osixia/phpldapadmin
    container_name: phpldapadmin
    ports:
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
    restart: always

  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    hostname: '116.63.170.231'
    container_name: gitlab
    environment:
        GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://116.63.170.231:8090'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        # Add any other gitlab.rb configuration here, each on its own line


        #gitlab 轻量化配置
        gitlab_rails['time_zone'] = 'Asia/Shanghai'

        # 关闭电子邮件相关功能
        gitlab_rails['smtp_enable'] = false
        gitlab_rails['gitlab_email_enabled'] = false
        gitlab_rails['incoming_email_enabled'] = false

        # Terraform
        gitlab_rails['terraform_state_enabled'] = false

        # Usage Statistics
        gitlab_rails['usage_ping_enabled'] = false
        gitlab_rails['sentry_enabled'] = false
        grafana['reporting_enabled'] = false

        # 关闭容器仓库功能
        gitlab_rails['gitlab_default_projects_features_container_registry'] = false
        gitlab_rails['registry_enabled'] = false
        registry['enable'] = false
        registry_nginx['enable'] = false

        # 包仓库
        gitlab_rails['packages_enabled'] = false
        gitlab_rails['dependency_proxy_enabled'] = false

        # GitLab KAS
        gitlab_kas['enable'] = false
        gitlab_rails['gitlab_kas_enabled'] = false

        # Mattermost
        mattermost['enable'] = false
        mattermost_nginx['enable'] = false

        # Kerberos
        gitlab_rails['kerberos_enabled'] = false
        sentinel['enable'] = false

        # GitLab Pages
        gitlab_pages['enable'] = false
        pages_nginx['enable'] = false

        # 禁用 PUMA 集群模式
        puma['worker_processes'] = 0
        puma['min_threads'] = 1
        puma['max_threads'] = 1

        # 降低后台守护进程并发数
        sidekiq['max_concurrency'] = 1

        gitlab_ci['gitlab_ci_all_broken_builds'] = false
        gitlab_ci['gitlab_ci_add_pusher'] = false

        # 关闭监控
        prometheus_monitoring['enable'] = false
        alertmanager['enable'] = false
        node_exporter['enable'] = false
        redis_exporter['enable'] = false
        postgres_exporter['enable'] = false
        pgbouncer_exporter['enable'] = false
        gitlab_exporter['enable'] = false
        grafana['enable'] = false
        sidekiq['metrics_enabled'] = false
    ports:
        - '8090:8090'
        - '2224:22'
    volumes:
        - /docker/gitlab_dir/etc/gitlab:/etc/gitlab'
        - /docker/gitlab_dir/var/log/gitlab:/var/log/gitlab'
        - /docker/gitlab_dir/var/opt/gitlab:/var/opt/gitlab'
