version: '3'
services:
  mongo:
    image: mongo:4.2.3
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hcq@
    ports:
      - '27017:27017'
    volumes:
      - '/docker/mongdb_dir/data/db:/data/db'
    restart: always

  mysql:
    image: mysql:8.0.18
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - '/docker/mysql_dir/var/lib/mysql:/var/lib/mysql'
      - '/docker/mysql_dir/etc/mysql/conf.d:/etc/mysql/conf.d'
      - '/docker/mysql_dir/var/log:/var/log'
    environment:
      MYSQL_ROOT_PASSWORD: 'hcq@'
    restart: always

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins_master
    user: root
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - '/docker/jenkins_dir/var/jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always

  ubuntu:
    image: ubuntu:22.04
    #    build: ./add_jenkins_node/
    container_name: jenkins_service_1
    network_mode: 'host'
    volumes:
      - '/docker/ubuntu_dir/tmp:/tmp'
      - './add_jenkins_node.sh:/add_jenkins_node.sh' #进入容器执行该脚本
    command: /bin/bash
    tty: true
    restart: always